### ISSUE TITLE
[Looping Critical Error!] Something is conflicting with plugins

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/BanSystemNK#5] opened 2020-04-14 06:39 UTC
I have a critical looping error when I use this plugin, Luckperm, and ZChat. What plugin make this endless error?

Log:
http://nukkitx.eu/uxibumufez.css

**Comment by PocketMiner82** [comment] 2020-04-18 10:42
I think the error is caused by ZChat.

**Comment by good777LUCKY** [comment] 2020-04-18 13:08
ok, i will ask ZChat developer, too.

**Comment by Mundschutziii** [comment] 2020-04-20 05:33
Thanks for your report.
A fix will be published in the next few days. I will probably have to put a small cool down when a player joins the game to prevent this mistake from happening again.

**Comment by good777LUCKY** [comment] 2020-04-20 11:11
thank you!

**Comment by Mundschutziii** [comment] 2020-04-23 15:09
The error should be fixed now.
https://nukkitx.com/resources/bansystem.332/updates#resource-update-1115

**Closed by Mundschutziii** 2020-04-23 15:09 UTC
Labels: bug report
